config/routes.rb
Rails.application.routes.draw do
  resources :exams
   resources :marks
  
  root to:'home#index'
  get 'home/about_us'
  get 'home/contact_us'
  get 'home/branches'
  # get 'home/student_information'
  devise_for :users
	get 'students/list'
	get 'students/new'
	post 'students/create'
	patch 'students/update'
	get 'students/list'
	get 'students/show'
	get 'students/edit'
	get 'students/delete'
	get 'students/update'
	get 'students/show_levels'
	get 'students/levels'
	get 'students/get_students'
	get "/get_students" ,to: "students#get_students"
	get "/get_names" ,to: "marks#get_names"
end	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
	# EXAMS=["quaterly","half_yearly","annual_exam"]
end

app/models/level.rb
class Level < ApplicationRecord
	has_many :students
end

app/models/mark.rb
class Mark < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage/
# Validate filename
	validates_attachment_file_name :avatar, matches: [/png\z/, /jpe?g\z/]
	validates :name, presence: true
	belongs_to :level
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
	before_action :authenticate_user!
	def index
		@exams=Exam.all
	end	

	def new
		@exam=Exam.new
	end	

	def create
		@exam=Exam.create(exam_params)
		redirect_to exams_path
	end
	private
	def exam_params
		params.require(:exam).permit(:exam_name)
	end		
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
	before_action :authenticate_user!
	def index
		@marks=Mark.all
	end	

	def new
		@mark=Mark.new
	end	

	def create
		@mark=Mark.create(mark_params)
		redirect_to marks_path
	end
	def show
		@mark=Mark.find(params[:id])
	end	

	def destroy
		@mark=Mark.find(params[:id]).destroy
		redirect_to marks_path
	end	

	def get_names
		@students=Student.where(:level_id => params[:state])
		# binding.pry	
		respond_to do |format|
        	format.js
      	end 

	end	

	private
	def mark_params
		params.require(:mark).permit(:exam_type,:telugu_marks,:maths_marks,:hindi_marks,:student_id,:exam_id,:level_id)
	end	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!
	def list
		@students = Student.all
	end
	def show
		@student = Student.find(params[:id])
	end
	def new
		@student = Student.new
		@levels = Level.all
	end
	def student_params
		params.require(:student).permit(:name, :level_id, :fathername, :email_id, :contact_no, :date_of_birth,
     :date_of_joining, :address,:avatar)
	end
	def create
		@student = Student.new(student_params)
		if @student.save
			redirect_to :action => 'list'
		else
			@levels = Level.all
			render :action => 'new'
		end
	end
	def edit
		@student = Student.find(params[:id])
		@levels = Level.all
	end
	def student_param
		params.require(:student).permit(:name, :level_id, :fathername, :email_id, :contact_no,:date_of_birth, :date_of_joining, :address,:avatar)
	 end
	def update
		@student = Student.find(params[:id])
		if @student.update_attributes(student_param)
			redirect_to :action => 'show', :id => @student
		else
			@levels = Level.all
			render :action => 'edit'
		end
	end
	def delete
		Student.find(params[:id]).destroy
		redirect_to :action => 'list'
		
	end
	def show_levels
		@level = Level.find(params[:id])
	end
	def levels
		
	end	
	def get_students
		@students=Student.where(:level_id => params[:state])
		respond_to do |format|
        	format.js
      	end 

	end	
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/exams/new.html.haml
/ - binding.pry
= simple_form_for(@exam) do |f|
  = f.collection_select :exam_name, Exam.all, :id, :exam_name,:include_blank => 'Please Select' 
/ = form_tag :action => 'create' do
/   %p
/     %label{for: "exams_exam_name"}>exams
/     = select_tag "exam", options_from_collection_for_select(Exam.all, "id", "exam_name"), :include_blank => 'Please Select'  

app/views/home/_carousel.html.haml
#myCarousel.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  / Wrapper for slides
  .carousel-inner
    .item
      =image_tag('1.jpeg')
    .item.active
      = image_tag('2.jpeg')
    .item
      = image_tag('3.jpeg')
  / Left and right controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
    %span.glyphicon.glyphicon-chevron-left
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
    %span.glyphicon.glyphicon-chevron-right
    %span.sr-only Next
/ #carouselExampleFade.carousel.slide.carousel-fade{"data-ride" => "carousel"}
/   .carousel-inner
/     .carousel-item.active
/       %img.d-block.w-100{:alt => "First slide", :src => "1.jpeg"}/
/     .carousel-item
/       %img.d-block.w-100{:alt => "Second slide", :src => "2.jpeg"}/
/     .carousel-item
/       %img.d-block.w-100{:alt => "Third slide", :src => "3.jpeg"}/
/   %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleFade", :role => "button"}
/     %span.carousel-control-prev-icon{"aria-hidden" => "true"}
/     %span.sr-only Previous
/   %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleFade", :role => "button"}
/     %span.carousel-control-next-icon{"aria-hidden" => "true"}
/     %span.sr-only Next

app/views/home/about_us.html.haml
%h1 About us
%p
  Choosing the right school is one of the most important decisions that you as a parent can take in your child’s life. From the first step into school to graduating with confidence and competence of an intellectually stimulating career – Silver Oaks can make all the difference.

app/views/home/branches.html.haml
%p
  HYDERABAD,
  %br/
  GUNTUR,
  %br/
  VIJAYAWADA,
  %br/
  NELLURE
  %br/
  ONGOLE
  %br/
  KAAKINADA

app/views/home/contact_us.html.haml
%p
  Road No: 71,
  %br/
  Jubilee Hills,
  %br/
  Hyderabad – 500096,
  %br/
  Telangana, India,
  %br/
  Ph: +91-40-23548584/ 23607797,
  %br/
  Email: info@jhpublicschool.com,
  %br/

app/views/home/index.html.haml
- unless user_signed_in?
  = render partial: 'carousel' 
/ %ul.nav.nav-tabs
/   %li.nav-item
/     %a.nav-link.active
/       = link_to('Student Detailes',  students_list_path)
/   %li.nav-item
/     %a.nav-link
/       = link_to('Levels',  students_levels_path) 
/   %li.nav-item
/     %a.nav-link{:href => "#"} Link
/   %li.nav-item
/     %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled

/ %li.active
/         = link_to('Home',  students_list_path)

app/views/layouts/_footer.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    :css
      .footer {
         position: fixed;
         left: 0;
         bottom: 0;
         width: 100%;
         background-color: blue;
         color: white;
         text-align: center;
      }
  %body
    .footer
      %p Footer

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %a.navbar-brand{:href => "#"} WebSiteName
    %ul.nav.navbar-nav
      %li.active
        = link_to('Home',  students_list_path)
      %li
        = link_to('About Us',  home_about_us_path)
      %li
        = link_to('Branches',  home_branches_path)
      %li
        = link_to('Contact Us',  home_contact_us_path)
     
    %ul.nav.navbar-nav.navbar-right.nav-pills
      - if user_signed_in? 
        %li
          / = redirect_to students_list_path 
          = link_to('Logout', destroy_user_session_path, method: :delete)
      - else
        %li
          / = redirect_to students_view_path 
          = link_to('Login', new_user_session_path)
          = link_to('Register', new_user_registration_path)

app/views/layouts/_nav_tabs.html.haml
%ul.nav.nav-tabs
  %li.nav-item
    %a.nav-link.active
      = link_to('Student Detailes',  students_list_path)
  %li.nav-item
    %a.nav-link
      = link_to('Levels',  students_levels_path) 
  %li.nav-item
    %a.nav-link
      = link_to('Exams', new_exam_path)  
  %li.nav-item
    %a.nav-link
      = link_to('Marks', marks_path)        

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title StudentProject
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
  = render partial: 'layouts/header' 
  = render partial: 'layouts/nav_tabs'
  = render partial: 'layouts/footer'
  .container
    %body    
      = yield

app/views/layouts/levels.html.haml
%h1 School Info
%p These are the levels in our school.
%table#levels
  %tr
    %th Levels
  - Level.find_each do |c|
    %tr
      %td= link_to c.id, :action => "show_levels", :id => c.id
= link_to 'Back', {:action => 'list'}
%hr/

app/views/marks/get_names.js.haml
$('#mark_student_id').empty();

- if @students.present?
  - @students.each do |student|
    $('#mark_student_id').append($('<option value="#{student.id}">#{student.name}</option>'));

app/views/marks/index.html.haml
%table.table
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} Exam 
      %th{:scope => "col"} student Name
      %th{:scope => "col"} level Name
      %th{:scope => "col"} Maths
      %th{:scope => "col"} Telugu
      %th{:scope => "col"} Hindi
     
      / %th{:scope => "col"} exam_id
      / %th{:scope => "col"} avatar

  %tbody
    - @marks.each do |c|
      %tr
        %th{:scope => "row"}
        %td= Exam.find_by(id:c.exam_id).exam_name      
        %td= Student.find_by(id:c.student_id).name
        %td= Level.find_by(id:c.level_id).level_number
        %td= c.maths_marks
        %td= c.telugu_marks
        %td= c.hindi_marks
        %td= link_to 'Destroy', mark_path(c),method: :delete,data: { confirm: 'Are you sure?' }
        / %td= c.exam_id
        / %td= image_tag c.avatar.url(:thumb)
= link_to 'Back', students_list_path        

app/views/marks/new.html.haml
= simple_form_for(@mark) do |f|
  / = f.collection_radio_buttons :exam_id, Exam.all, :id , :exam_name
  = f.label :level_id 
  = f.collection_select :level_id, Level.all, :id, :level_number,:include_blank => 'Please Select'
  = f.label :student_id
  = f.collection_select :student_id, Student.all, :id, :name,:include_blank => 'Please Select'
  = f.input :exam_id
  = f.input :telugu_marks
  = f.input :hindi_marks
  = f.input :maths_marks 
  = f.button :submit
= link_to 'Back', students_list_path

app/views/students/_form.html.haml
%table.table
  %thead
    %tr
      %th{:scope => "col"} #
      %th{:scope => "col"} name
      %th{:scope => "col"} fathername
      %th{:scope => "col"} email_id
      %th{:scope => "col"} contact_no
      %th{:scope => "col"} date_of_birth
      %th{:scope => "col"} date_of_joining
      %th{:scope => "col"} address
      %th{:scope => "col"} avatar

  %tbody
    - @students.each do |c|
      %tr
        %th{:scope => "row"}
        %td= c.name
        %td= c.fathername
        %td= c.email_id
        %td= c.contact_no
        %td= c.date_of_birth
        %td= c.date_of_joining
        %td= c.address
        %td= image_tag c.avatar.url(:thumb)

app/views/students/edit.html.haml
%h1 Edit Student Detail
= form_for @student, :url => {:action => "update", :id => @student} do |f|
  %p
    Name: #{f.text_field 'name'}
  %p
    = f.collection_select :level_id, Level.all, :id, :level_number
  %p
    English marks: #{f.text_field 'english_marks'}
  %p
    Math marks: #{f.text_field 'math_marks'}
  %p
    Science marks: #{f.text_field 'science_marks'}
  = f.submit "Save changes"
%hr/
= link_to 'Back', {:action => 'list'}

app/views/students/get_students.js.haml
$(".students_list").empty();
var page_html = "#{escape_javascript( render partial: 'form', locals: { students: @students} )}"
/ - binding.pry
$(".students_list").append(page_html)

app/views/students/levels.html.haml
= form_tag :action => 'create' do
  %p
    %label{for: "students_level_id"}>Level
    = select_tag "level", options_from_collection_for_select(Level.all, "id", "level_number"), :include_blank => 'Please Select'
.students_list

%hr/
= link_to 'Back', {:action => 'list'}

app/views/students/list.html.haml
= link_to "Add new Student", {:action => 'new'}
%hr/
= link_to "Add new marks", new_mark_path

  

/ %table#levels
/   %tr
/     %th Levels
/   - Level.find_each do |c|
/     %tr
/       %td= link_to c.id, :action => "show_levels", :id => c.id
/ %p
/ %hr/
/ = link_to "Add new Student", {:action => 'new'}


/ %h1 Student Info
/ - if @students.blank?
/   %p There are no students in the school.
/ - else
/   %p These are the students in our school.
/   %table#students
/     %tr
/       %th Names
/       %th Levels
/     - @students.each do |c|
/       %tr

/         %td= image_tag c.avatar.url(:thumb)
/         %td= link_to c.name, {:action => 'show', :id => c.id}
/         %td= c.level_id
/         %td
/           = link_to 'Edit', {:action => "edit", :id => c.id}
/           |
/         %td= link_to "Delete", {:action => 'delete', :id => c.id}, data: {:confirm => "Are you sure you want to delete this record?"}
/ %p
/ = link_to 'Back', {:action => 'list'}

app/views/students/new.html.haml
%h1 Student Details
- if @student.errors.any?
  #error_explanation
    %h2
      = pluralize(@student.errors.count, "error")
      Prohibited the details from being saved:
    %ul
      - @student.errors.full_messages.each do |msg|
        %li= msg
= form_for @student , url: students_create_path, html: { multipart: true } do |form|
  %p
    = form.label :name
    = form.text_field :name
  %p
    = form.label :level
    = form.collection_select(:level_id, Level.all, :id, :level_number)
  %p
    = form.label :fathername
    = form.text_field :fathername
  %p
    = form.label :email_id
    = form.text_field :email_id
  %p
    = form.label :contact_no
    = form.text_field :contact_no
  %p
    = form.label :date_of_birth
    = form.text_field :date_of_birth
  %p
    = form.label :date_of_joining
    = form.text_field :date_of_joining
  %p
    = form.label :address
    = form.text_area :address
  %p
    = form.file_field :avatar

  %p
    = form.submit
  
  = link_to 'Back', {:action => 'list'}
%hr/

app/views/students/show.html.haml
%div{align: "center"}
  %h1 Progress Report
  %strong Name:
  = @student.name
  %p
    %strong Level:
    = @student.level.level_number
    %br/
    - if @student.english_marks < 35
      %h4{style: "color:Red;"}
        %strong English marks:
        = @student.english_marks
    - else
      %strong English marks:
      = @student.english_marks
      %br/
    - if @student.math_marks < 35
      %h4{style: "color:Red;"}
        %strong Math marks:
        = @student.math_marks
    - else
      %strong Math marks:
      = @student.math_marks
      %br/
    - if @student.science_marks < 35
      %h4{style: "color:Red;"}
        %strong Science marks:
        =@student.science_marks
    - else
      %strong Science marks:
      = @student.science_marks
      %br/
    Total:#{@student.english_marks+@student.math_marks+@student.science_marks}
    %br/
    Percentage:#{(@student.english_marks+@student.math_marks+@student.science_marks)/3}%
    = link_to 'Back', {:action => 'list'}

app/views/students/show_levels.html.erb
<h1>Level:<%= @level.level_number %></h1>
<table>
	<th>
		<td>Names</td>
	</th>
	<% @level.students.each do |c| %>
		<tr>
			<td><%= c.name %></td>
		</tr>
	<% end -%>
</table>
<hr>
<%= link_to 'Back', {:action => 'list'} %>